<a href="https://colab.research.google.com/github/PavelDaB/DeepLearningJourney/blob/main/tensorsandmathoperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [3]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [4]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [7]:
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [8]:
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [9]:
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [10]:
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [12]:
tensor_a / tensor_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [15]:
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [16]:
tensor_a % tensor_b

tensor([1, 2, 3, 4])

In [17]:
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [18]:
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [19]:
tensor_a

tensor([ 6,  8, 10, 12])